### ISSUE TITLE
spanish prepositions

### ISSUE THREAD

**Issue by stutzmann72** [pkp/citationStyleLanguage#100]
The prepositions in spanish (espagnol: Espagna) within the journal title are capitalized which is wrong. See screenshot. The styles APA, MLA and Chicago are concerned.

![2023-01-03_14-03-28](https://user-images.githubusercontent.com/31411045/210362945-f09dda02-6b83-4e48-9688-db45be581b26.png)

**Comment by asmecher** [comment]
@stutzmann72, OJS uses the (excellent) third-party [citeproc-php](https://github.com/seboettg/citeproc-php) library for formatting citations; the capitalization in your screenshot is being performed by that code.

At a glance, it looks like the preposition list that prevents unwanted capitalization in these cases is [hard-coded in English](https://github.com/seboettg/citeproc-php/blob/develop/src/Util/StringHelper.php#L24..L27).

If you would like the developer to consider changing that, I'd suggest filing an issue in that repository by filling out [this form](https://github.com/seboettg/citeproc-php/issues/new).
