### ISSUE TITLE
Journal with & in the title

### ISSUE THREAD

**Issue by orcalator** [pkp/citationStyleLanguage#103]
Hi,

Article citation has some bug regarding & char in the title of the journal. You can see it here: https://hrcak.srce.hr/ojs/index.php/slpdj/article/view/23237. "amp" is added twice for some reason.

regards.

**Comment by orcalator** [comment]
Is seems you are doing double htmlspecialchars escape. I changed this line in CitationStyleLanguagePlugin.inc.php:
 `$citationData->{'container-title'} = htmlspecialchars($context->getLocalizedName());`
to
 `$citationData->{'container-title'} = $context->getLocalizedName();`
and now it's fine.

**Comment by asmecher** [comment]
@orcalator, this is a duplicate of https://github.com/pkp/pkp-lib/issues/6986, which has been fixed since OJS 3.3.0-8.
