### ISSUE TITLE
Double encoding on citations

### ISSUE THREAD

**Issue by paulo-graca** [pkp/citationStyleLanguage#118]
I think this issue we have is related with this one: https://github.com/pkp/citationStyleLanguage/issues/95

Currently we have a journal which names "Cinema & Território" and, in the citation, the name appears encoded like:
`Baía Reis, A., Mendes, G., Rebanda Coelho, I., & Norton Dias, T. (2023). Editorial | A Direção da C&amp;T. Cinema &Amp; Território, (8), 7.[ https://doi.org/10.34640/c.t8uma2023editorial](https://doi.org/10.34640/c.t8uma2023editorial)
`
I've found if I remove the `htmlspecialchars` function at line 320: CitationStyleLanguagePlugin.inc.php (https://github.com/pkp/citationStyleLanguage/blob/3_2_1-2/CitationStyleLanguagePlugin.inc.php#L320):
```php
$citationData->{'container-title'} = htmlspecialchars($context->getLocalizedName());
```
the name appear correctly with one single encoding. I'm guessing that, besides this one, a second encoding occurs at the template level. So my thoughts go to have only one, but which one?

PRs:
stable-3_4_0:
- https://github.com/pkp/citationStyleLanguage/pull/122
- https://github.com/pkp/ojs/pull/4342 (only submodule update)
- https://github.com/pkp/omp/pull/1616 (only submodule update)
- https://github.com/pkp/ops/pull/720 (only submodule update)

main:
- https://github.com/pkp/citationStyleLanguage/pull/125

**Comment by bozana** [comment]
@jonasraoni, may I ask you again to review the PR above? 
The PR also solves https://github.com/pkp/citationStyleLanguage/issues/95.
Thanks a lot!
