### ISSUE TITLE
The prefixes and suffixes of the DOI and URL citation element should not be linked

### ISSUE THREAD

**Issue by bozana** [pkp/citationStyleLanguage#120]
See:
<img src="https://github.com/pkp/citationStyleLanguage/assets/378421/dd6f15f8-5742-4104-aa49-0b9beef835d9" alt="Screenshot from 2024-06-26 13-20-28" width="250">

Regarding DOI citation part:
Depending on the citation style, the DOI part could have the prefixes 'DOI:' or 'doi:' with a white space '' or even with a dot '. ' before it, e.g. ('. DOI:' in ACM style).
Suffix can be a dot '.'.

PRs:
stable-3_4_0: 
- https://github.com/pkp/citationStyleLanguage/pull/121
- https://github.com/pkp/ojs/pull/4341 (only submodule udpate)
- https://github.com/pkp/omp/pull/1613 (only submodule udpate)
- https://github.com/pkp/ops/pull/719 (only submodule udpate)

main:
- https://github.com/pkp/citationStyleLanguage/pull/123

**Comment by bozana** [comment]
Hi @jonasraoni, could you please review the PR above?
When everything OK, I would port it to main.
Thanks a lot!

**Comment by jonasraoni** [comment]
@bozana the stable branches were merged with the wrong commit, I've updated.

**Comment by bozana** [comment]
:-O 
thanks @jonasraoni 
:-O
