### ISSUE TITLE
version.xml should be updated

### ISSUE THREAD

**Issue by mpbraendle** [pkp/citationStyleLanguage#129]
version.xml still has 

`<release>0.1.0.0</release>
<date>2017-06-28</date>`

which makes it difficult to identify whether the plugin was updated in the meantime and keep track of the version, since this plugin is not part of the plugin gallery.

The release number and date should be updated regularly.

**Comment by asmecher** [comment]
@mpbraendle, the citationStyleLanguage plugin is included in the OJS distribution, and we don't release it independently from that (although we could -- in which case we would bump the verison number).
