### ISSUE TITLE
citationStyleLanguage: error

### ISSUE THREAD

**Issue by viktorholzwert** [pkp/citationStyleLanguage#138]
We are running an 3.3.0-20 ojs instance. 

While switching the citation style from anything to chicago style we see nothing happens in the frontend but receive the following error log: 

[Tue Dec 10 10:32:21.003282 2024] [php:error] [pid 542:tid 542] [client 172.18.0.3:56468] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string % int in /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/
citeproc-php/src/Util/PageHelper.php:83\nStack trace:\n#0 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Util/PageHelper.php(44): Seboettg\\CiteProc\\Util\\PageHelper::renderChicago()\n#1 /var/www/html
/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Text.php(162): Seboettg\\CiteProc\\Util\\PageHelper::processPageRangeFormats()\n#2 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/ci
teproc-php/src/Rendering/Text.php(108): Seboettg\\CiteProc\\Rendering\\Text->renderPage()\n#3 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Choose/ChooseIf.php(79): Seboettg\\CiteProc\\Rende
ring\\Text->render()\n#4 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Choose/Choose.php(83): Seboettg\\CiteProc\\Rendering\\Choose\\ChooseIf->render()\n#5 /var/www/html/plugins/generic/cita
tionStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Choose/ChooseIf.php(79): Seboettg\\CiteProc\\Rendering\\Choose\\Choose->render()\n#6 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rend
ering/Choose/Choose.php(98): Seboettg\\CiteProc\\Rendering\\Choose\\ChooseIf->render()\n#7 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Style/Macro.php(86): Seboettg\\CiteProc\\Rendering\\Choose\\Cho
ose->render()\n#8 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Text.php(290): Seboettg\\CiteProc\\Style\\Macro->render()\n#9 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/s
eboettg/citeproc-php/src/Rendering/Text.php(120): Seboettg\\CiteProc\\Rendering\\Text->renderMacro()\n#10 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Layout.php(130): Seboettg\\CiteProc\\R
endering\\Text->render()\n#11 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Layout.php(97): Seboettg\\CiteProc\\Rendering\\Layout->renderSingle()\n#12 /var/www/html/plugins/generic/citationS
tyleLanguage/lib/vendor/seboettg/citeproc-php/src/Style/Bibliography.php(76): Seboettg\\CiteProc\\Rendering\\Layout->render()\n#13 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/CiteProc.php(137): Sebo
ettg\\CiteProc\\Style\\Bibliography->render()\n#14 /var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/CiteProc.php(183): Seboettg\\CiteProc\\CiteProc->bibliography()\n#15 /var/www/html/plugins/generic/cita
tionStyleLanguage/CitationStyleLanguagePlugin.inc.php(423): Seboettg\\CiteProc\\CiteProc->render()\n#16 /var/www/html/plugins/generic/citationStyleLanguage/pages/CitationStyleLanguageHandler.inc.php(45): CitationStyleLanguagePlugin->getCitatio
n()\n#17 /var/www/html/lib/pkp/classes/core/PKPRouter.inc.php(397): CitationStyleLanguageHandler->get()\n#18 /var/www/html/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()\n#19 /var/www/html/lib/
pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()\n#20 /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php(360): Dispatcher->dispatch()\n#21 /var/www/html/index.php(68): PKPApplication->execute()\n#22 {main}\n  thrown in /
var/www/html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Util/PageHelper.php on line 83, referer: https://abc.test.ub.uni-bamberg.de/jfr/article/view/131

**Comment by asmecher** [comment]
@viktorholzwert, this is an issue in the 3rd-party citeproc-php library we use to format citation styles:

https://github.com/seboettg/citeproc-php/issues/144

In the future, I'd suggest starting with our support forum (https://forum.pkp.sfu.ca) rather than filing an issue here.
