### ISSUE TITLE
Primary Citation Format can't be selected when not set as Additional Citation Formats

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/citationStyleLanguage#22]
One of our editors chose MLA as our Primary Citation Format. As _Additional Citation Formats_ only Chicago was chosen. When you are now on the article page you can change the citation format from MLA to Chicago. But after that you are unable to change the citation style back to MLA because only the _Additional Citation Formats_ are listed in the drop down.

I think it is not very obvious that you have to select the _Primary Citation Format_ as an _Additional Citation Format_ in order to select it again. I propose to always show the _Primary Citation Format_ as an option in the drop down, even when the format is not selected as _Additional Citation Format_.

**Comment by NateWr** [comment]
Hi @MarHerUMR. Seems like a reasonable expectation. I'm closing down issues on this repo to centralize them in our `pkp-lib` repository. I've ported this over to there: https://github.com/pkp/pkp-lib/issues/3353
