### ISSUE TITLE
[QUESTION] Is this version compatible with OJS 3.3.x?

### ISSUE THREAD

**Issue by evertramos** [pkp/citationStyleLanguage#96]
Hello there! (newbie here...)

I would like to confirm if the plugin version 3.3.0 is compatible with OJS 3.3.x?

I am getting an error as of follow:

```log
[Thu Jun 23 15:59:57.486677 2022] [php7:error] [pid 107] [client 10.74.16.113:34594] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/ojs/plugins/generic/citationStyleLanguage/lib/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/ojs/plugins/generic/citationStyleLanguage/CitationStyleLanguagePlugin.inc.php on line 17
```

In the file `CitationStyleLanguagePlugin.inc.php` has the `require_once(__DIR__ . '/lib/vendor/autoload.php');`, but in our instalation the folder `./ojs/lib/` has only a folder called `bkp`.

So, I am not sure if our instalation has a bug itself, we should somehow run a composer install to get the vendor or if the plugin is not compatible with the version 3.3.x.

Thanks.

**Comment by asmecher** [comment]
@evertramos, the plugin is included with OJS, so I'd recommend using the files that come with the OJS package. Getting the files from Github will result in missing composer dependencies, as you've seen, but it's also likely you'll get an incompatible version of the plugin code.

**Comment by evertramos** [comment]
@asmecher thank you very much for you reply!!!
