### ISSUE TITLE
Citation year incorrect

### ISSUE THREAD

**Issue by eddoff** [pkp/citationStyleLanguage#99]
When an article is published in an ahead-of-print issue first when accepted (say 2021), and then it is transferred to an issue with publication year 2022, the citation year is still 2021 and not changed to 2022 which it should according to reference rules. 

I request that you add an option to the plugin to choose if the displayed year should be based on publication date of the article or the publication date of the issue. A similar option is available for the copyright year.

**Comment by eddoff** [comment]
Another issue is when older journal issues are digitized, and published online. A journal issue printed in 2000, that was first online published in 2016, has an article publication date in 2016, and an issue publication date from 2016, but the issue year is 2000. 

For example:
Issue: https://socvet.se/issue/view/260 publication date: 2016-02-05, and issue year 2000
Article:  https://socvet.se/article/view/2820 publication date 2016-02-05.

In this case it should be great if the issue year could be chosen as citation year!

One thing that might cause problem is if the publication scheme changes during the years. So if it is possible to change the default displayed citation year it should also be possible to manually change the displayed citation year for each publication (in analogy to the copyright year).

**Comment by eddoff** [comment]
Thanks for fast reply!

But I don't wish to change the publication date to a later date when moving the article into an issue. The first publication date should be the one that is visible on the article landing page. However, the citation year should in most citation guides be the year of the issue publication, not the year when the article was first online.

What about the second issue then? Is it possible to add a separate field for the displayed citation year in order to do a work-around for the older content?

**Comment by NateWr** [comment]
I don't think citations are meant to change in that way. I'd suggest discussing this in our [community forum](https://forum.pkp.sfu.ca/) to see if anyone has good ideas for how to handle your use case.
